use sql_hr;
select * from employees;
select employee_id from employees order by salary desc;
use store;
select * from customers;
select * from products;
select * from orders;
select sum(quantity_in_stock) as TOTAL from products;
select * from order_items;
select sum(quantity) from order_items;
select sum(quantity * 10) from order_items;
select * from employees limit 10;
select employee_id,first_name, salary from employees  where salary <= 90000 limit 10;
select unit_price from products where unit_price is not null;
select unit_price from products where unit_price is null;
select avg(salary) from employees;
select avg(salary) as AVERAGESALARY from employees; 
select * from products where name like "F_%";
select * from products where name like "shirt";
select * from products where name like "B%e";
select * from products where name like "A%";
select * from products where unit_price between 1.5 and 2.5;
select name from products where unit_price between 1.5 and 2.5;
select * from orders where order_date between "2017-06-01" and "2018-06-01";
select * from order_items where unit_price between 1.5 and 9.5 and product_id in (1,2,3);
select * from employees where job_title in ("Social Worker", "Staff Scientist", "Assistant Professor");